### ISSUE TITLE
There is a bug in euler_spiral.cpp !!!!

### ISSUE THREAD

**Issue by meng216073** [CoffeeKumazaki/euler_spiral#1]
hello, thank you for your opensource code. solve my question. 
however, I found the bug in the process of using. 

the origin code:
`pos.x = M_PI * a * (x * cos(theta) - y * sin(theta)); `
`pos.y = M_PI * a * (x * sin(theta) + y * cos(theta));  `
`if (dCurv < 0.0)  pos.x *= -1.0;  `

the fix code:
`if (dCurv < 0.0) x *= -1.0;`    
   ` pos.x = M_PI * a * (x * cos(theta) - y * sin(theta)); ` 
   ` pos.y = M_PI * a * (x * sin(theta) + y * cos(theta));  `

because in the paper sign is for the x not the pos.x.

**Comment by CoffeeKumazaki** [comment]
Hi @meng216073 !
Thanks for reporting the bug. That's exactly the bug I am facing.

**Comment by CoffeeKumazaki** [comment]
fixed at 5e5813c9c8cf1cab1316a8d3d36d411de17d275a
