### ISSUE TITLE
make only output the libeuler_spiral_lib.a file

### ISSUE THREAD

**Issue by wx100059** [CoffeeKumazaki/euler_spiral#2]
I executed the command but only get the `libeuler_spiral_lib.a`. No executable file generated. Could any one teach me the following step to get the plot shown in ReadMe? Thanks very much!

**Comment by CoffeeKumazaki** [comment]
Thank you for your feedback.
How about this procedure?
```
$ mkdir build
$ cd build
$ cmake ../test/
$ make
```

**Comment by CoffeeKumazaki** [comment]
Fixed so that demo can be built on Ubuntu as well
